language: php

php:
  - 7.2

before_script:
#  - cp .env.travis .env
#  - mysql -e 'create database homestead_test;'
  - cd image-uploader
  - composer install --no-interaction
#
#script:
#  - vendor/bin/phpunit

branches:
  only:
    - master
